version: '3.3'

services:
  python:
    container_name: JLTS_python
    build:
        context: ./
        dockerfile: ./docker/python/Dockerfile
    image: "bitnami/python:${PYTHON_VERSION}"
    tty: true
    ports:
      - 8000:8000
      - 9001:9001 # Access GUI with http://localhost:9001/
    volumes:
      - "./src:/app"
    networks:
      public_net:
        ipv4_address: 10.10.10.10

networks:
  public_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.10.0/24
