---

- name: Install supervisor
  apt:
    name: supervisor
    state: present

- name: Send supervisord.conf
  copy:
    src: supervisord.conf
    dest: /etc/supervisor/supervisord.conf
    owner: root
    group: root
    mode: 0644

- name: Send conf.d/* app configs
  synchronize:
    src: conf.d
    dest: /etc/supervisor/
    recursive: True
    delete: True

- name: run supervisord
  command: "/usr/bin/supervisord -c /etc/supervisor/supervisord.conf"
