---

- name: "Determine penultimate build"
  shell: ls -d /path/to/project/builds/* | tail -n +{{ keep_releases }} | head -1
  register: penultimate_build

- name: "Update current release symlink"
  file:
      state: link
      force: yes
      path: "{{ current_web_release_dir }}"
      src: "{{ penultimate_build.stdout }}"

- name: "Reload supervisord"
  service:
      name: "supervisord"
      state: "reloaded"

- name: "Restart uwsgi"
  command: "supervisorctl restart uwsgi"
