---

- name: Install cron
  apt:
    name: cron
    state: present

- shell: ls -1 /etc/cron.d
  register: oldjobs

- name: Empty directory for old files
  file:
    path: /etc/cron.d/{{ item }}
    state: absent
  with_items: "{{ oldjobs.stdout_lines }}"

- name: Send all cron tasks
  copy:
    src: jobs/
    dest: /etc/cron.d
    owner: root
    group: root
    mode: 0644

# - name: Ensure crons are 0644
#   command: chmod 0644 /etc/cron.d/*

- name: Create cron log file
  file:
    path: /var/log/cron.log
    state: touch
  register: p
  changed_when: p.diff.before.state == "absent"

- name: Restart cron service
  service:
    name: cron
    state: restarted
