# docker:
#   - image: circleci/python:3.8.2
### implement test framework in the future. ###
# cd /home/circleci/app/src
# python3 -m venv venv
# . venv/bin/activate
# pip install -r requirements.txt

version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:202007-01
    working_directory: /home/circleci/app
    environment:
      - ANSIBLE_HOST_KEY_CHECKING: False
    steps:
      - add_ssh_keys:
          fingerprints:
            - "66:c2:db:1f:9b:b7:a7:d2:46:bc:e5:a2:96:a6:dc:db"
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "/home/circleci/app/src/requirements.txt" }}
      - run:
          name: Install Dependencies
          command: |
            pip install ansible
            sudo apt update
            sudo apt install rsync
      - save_cache:
          key: deps-{{ checksum "/home/circleci/app/src/requirements.txt" }}
      - run:
          name: Deploy to production
          command: |
            ansible-playbook -i /home/circleci/app/deployment/inventory/hosts /home/circleci/app/deployment/playbook.yml
