version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:202007-01
    working_directory: ~/app
    environment:
      - ANSIBLE_HOST_KEY_CHECKING: False
    steps:
      - add_ssh_keys:
          fingerprints:
            - "66:c2:db:1f:9b:b7:a7:d2:46:bc:e5:a2:96:a6:dc:db"
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "~/app/src/requirements.txt" }}
      - run:
          name: Push tag to repository
          command: |
            make tag
      - run:
          name: Install Dependencies
          command: |
            sudo apt update
            sudo apt install rsync
            pip3 install ansible
      - save_cache:
          key: deps-{{ checksum "~/app/src/requirements.txt" }}
          paths:
            - ~/temp
      - run:
          name: Deploy to production
          command: |
            TAG=$(git describe --tags --abbrev=0)
            ansible-playbook -i \
            ~/app/ansible/inventory/hosts \
            ~/app/ansible/playbook.yml \
            -e "CEMRETAG=${TAG}"
