version: 2.1

parameters:
  workingdir:
    type: string
    default: "/home/circleci/app"

jobs:
  build:
    working_directory: << pipeline.parameters.workingdir >>
    docker:
      - image: circleci/python:3.8.2
    environment:
      - ANSIBLE_HOST_KEY_CHECKING: False
      - ANSIBLE_LOCAL_TEMP: /home/circleci/.ansible/tmp
      - ANSIBLE_REMOTE_TEMP: /home/circleci/.ansible/tmp
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum << pipeline.parameters.workingdir >> "/src/requirements.txt" }}
      - run:
          name: Install Dependencies
          command: |
            pip install ansible
            pip install -r << pipeline.parameters.workingdir >>/src/requirements.txt
            sudo apt update
            sudo apt install rsync
      - save_cache:
          key: deps-{{ checksum << pipeline.parameters.workingdir >> "/src/requirements.txt" }}
          paths:
            - venv
      - run:
          name: Deploy to production
          command: |
            ansible-playbook -i << pipeline.parameters.workingdir >> /deployment/inventory/hosts << pipeline.parameters.workingdir >> /deployment/playbook.yml
