version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:202007-01
    working_directory: ~/app
    environment:
      - ANSIBLE_HOST_KEY_CHECKING: False
    steps:
      - add_ssh_keys:
          fingerprints:
            - "66:c2:db:1f:9b:b7:a7:d2:46:bc:e5:a2:96:a6:dc:db"
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "~/app/src/requirements.txt" }}
      - run:
          name: Push tag to repository
          command: |
            make tag
      - run:
          name: Install Dependencies
          command: |
            sudo apt update
            sudo apt install rsync
            pip3 install ansible
            pip3 install ansible-tower-cli
      - save_cache:
          key: deps-{{ checksum "~/app/src/requirements.txt" }}
          paths:
            - ~/temp
      - deploy:
          name: Deploy to production
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              TAG=$(git describe --tags --abbrev=0)
              tower-cli config host http://34.123.174.145
              tower-cli config username admin
              tower-cli config password ak64ck94
              tower-cli config verify_ssl False
              tower-cli job launch --monitor -J "JL2 Build" -e "tag=${TAG}"
            fi
