version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8.2
    environment:
      - ANSIBLE_HOST_KEY_CHECKING: False
      - ANSIBLE_LOCAL_TEMP: /home/circleci/.ansible/tmp
      - ANSIBLE_REMOTE_TEMP: /home/circleci/.ansible/tmp
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "requirements.txt" }}
      - run:
          name: Install Dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install ansible
            pip install -r requirements.txt
            sudo apt update
            sudo apt install rsync
      - save_cache:
          key: deps-{{ checksum "requirements.txt" }}
          paths:
            - venv
      - run:
          name: Deploy to production
          command: |
            . venv/bin/activate
            ansible-playbook -i deployment/hosts deployment/playbook.yml
