# Set interactive console timeout.
export TMOUT=900

# Timestamps for command history
export HISTTIMEFORMAT="%Y-%m-%d %H:%M:%S "

# Save history immediately
export PROMPT_COMMAND='history -a'

# Store more history
export HISTFILESIZE=1000000
export HISTSIZE=100000
