default:
  DATABASE:
    Driver: Mongo
    Mongo:
      Host: 2.tcp.ngrok.io  # Host: 127.0.0.1
      Port: 11682  # Port: 3001
      Database: meteor  # Database: meteor

  QUEUE:
    Driver: RabbitMQ
    RabbitMQ:
      Host: 138.68.63.142  # Host: 127.0.0.1
      Port: 5672  # Port: 5672
      Username: user  # Username: guest
      Password: bitnami  # Password: guest

  DOMAIN:
    Shopify:
      Queue:
        VirtualHost: /
        PendingTasks: DEBUG::Pending.Tasks.Queue
      API:
        Store: jl2shpfy.myshopify.com
        Version: 2019-10
        Token: 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

